const dataProducts = [
  {
    id: 1,
    img: 'img/product1.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },

  {
    id: 2,
    img: 'img/product2.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },

  {
    id: 3,
    img: 'img/product3.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },

  {
    id: 4,
    img: 'img/product4.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },

  {
    id: 5,
    img: 'img/product5.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },

  {
    id: 6,
    img: 'img/product6.jpg',
    title: "ELLERY X M'O CAPSULE",
    desc: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
    price: 52.0,
    currency: '$',
    color: 'red',
    size: 'XL',
    quantity: 0,
    amount: 15,
  },
];
